parser: "@typescript-eslint/parser"
env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/react
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react-hooks/rules-of-hooks: 2
  react/no-unused-prop-types: 2
  no-undef: 0 # flow handles this and eslint can't handle optional chaining
  new-cap: 0
  no-console: warn
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-explicit-any": 0
settings:
  react:
    version: "16.7"
